%%{init: {"theme": "forest", "themeVariables": {"primaryColor": "#f2f2f2", "primaryBorderColor": "#e61010", "primaryTextColor": "#01060d", "lineColor": "#0856f3", "fontFamily": "Arial"}}}%%
erDiagram
    ADMIN_USERS ||--o{ REFRESH_TOKENS : user_email
	CLIENT_USERS ||--o{ REFRESH_TOKENS : user_email
	CLIENT_USERS ||--o{ CLIENT_STORE_MAPPING : client_id
	STORES ||--o{ CLIENT_STORE_MAPPING : store_id
	STORES ||--o{ DAILY_REPORTS : store_id
	STORES ||--o{ MONTHLY_REPORTS : store_id
	STORES ||--o{ YEARLY_REPORTS : store_id
	

	ADMIN_USERS {
		Long admin_id PK
		String full_name
		String email
		String password_hash
		UserRole role
		LocalDateTime created_at
		LocalDateTime updated_at
	}

	CLIENT_USERS {
		Long client_id PK
		String full_name
		String email
		String password_hash
		String phone_number
		String address
		Status status
		UserRole role
		LocalDateTime created_at
		LocalDateTime updated_at
	}

	REFRESH_TOKENS {
		Long id PK
		String token_hash "SHA-256 hash of raw token"
		String user_email
		String user_role
		LocalDateTime expires_at
		Boolean revoked
		LocalDateTime created_at
	}

	STORES {
		Long store_id PK
		String store_name
		String store_code
		String address
		String contact_number
		Status status
		LocalDateTime created_at
		LocalDateTime updated_at
	}

	CLIENT_STORE_MAPPING {
		Long client_id PK,FK
		Long store_id PK,FK
		StoreRole role "OWNER or PARTNER"
		LocalDateTime created_at
		LocalDateTime updated_at
	}

	DAILY_REPORTS {
		Long daily_report_id PK
		Long store_id FK
		LocalDate report_date
		BigDecimal grocery_total
		BigDecimal volume
		BigDecimal cash_deposit
		BigDecimal check_deposit
		BigDecimal over_short
		BigDecimal no_sale
		BigDecimal line_void
		BigDecimal void_amount
		BigDecimal refunds
		LocalDateTime created_at
		LocalDateTime updated_at
	}

	MONTHLY_REPORTS {
		Long monthly_report_id PK
		Long store_id FK
		Integer report_month
		Integer report_year
		Integer department_id
		String department_name
		BigDecimal gross
		BigDecimal discount
		BigDecimal promotion
		BigDecimal refund
		BigDecimal void_amount
		BigDecimal net_sales
		LocalDateTime created_at
		LocalDateTime updated_at
	}

	YEARLY_REPORTS {
		Long yearly_report_id PK
		Long store_id FK
		Integer report_year
		String annual_summary
		LocalDateTime created_at
		LocalDateTime updated_at
	}
